services:
  # denis:
  #   build: ./backend
  #   ports:
  #     - "53:53/udp"
  #     - "53:53/tcp"
  #     - "8080:8080"
  #   environment:
  #     - REDIS_URL=redis://redis:6379
  #   depends_on:
  #     - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
