[package]
name = "dnsanalytics"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx = { version = "0.8", features = [ "runtime-tokio", "tls-native-tls" ] }
tokio = { version = "1.49.0", features = ["full"] }
hickory-proto = "0.25.2"
thiserror = "2"
